"""initial_schema

Revision ID: c4ae4cc6b2bc
Revises: 
Create Date: 2026-05-25 00:34:58.337294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c4ae4cc6b2bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bikes_make'), 'bikes', ['make'], unique=False)
    op.create_index(op.f('ix_bikes_model'), 'bikes', ['model'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('RIDER', 'VERIFIED_ENTHUSIAST', 'EXPERT_REVIEWER', 'BRAND_OFFICIAL', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='contributionstatus'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributions_contributor_id'), 'contributions', ['contributor_id'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bike_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('function', sa.Text(), nullable=False),
    sa.Column('failure_consequences', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Enum('SAFE', 'CAUTION', 'STOP', name='risklevel'), nullable=False),
    sa.Column('diy_fixable', sa.Boolean(), nullable=False),
    sa.Column('quick_fix', sa.Text(), nullable=True),
    sa.Column('cost_range_min', sa.Integer(), nullable=True),
    sa.Column('cost_range_max', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_risk_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_bike_id'), 'parts', ['bike_id'], unique=False)
    op.create_index(op.f('ix_parts_category'), 'parts', ['category'], unique=False)
    op.create_table('diy_guides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bike_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficulty'), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('tools_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diy_guides_bike_id'), 'diy_guides', ['bike_id'], unique=False)
    op.create_index(op.f('ix_diy_guides_part_id'), 'diy_guides', ['part_id'], unique=False)
    op.create_table('part_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_part_id', sa.UUID(), nullable=False),
    sa.Column('to_part_id', sa.UUID(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['to_part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_connections_from_part_id'), 'part_connections', ['from_part_id'], unique=False)
    op.create_index(op.f('ix_part_connections_to_part_id'), 'part_connections', ['to_part_id'], unique=False)
    op.create_table('guide_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['diy_guides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guide_steps_guide_id'), 'guide_steps', ['guide_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guide_steps_guide_id'), table_name='guide_steps')
    op.drop_table('guide_steps')
    op.drop_index(op.f('ix_part_connections_to_part_id'), table_name='part_connections')
    op.drop_index(op.f('ix_part_connections_from_part_id'), table_name='part_connections')
    op.drop_table('part_connections')
    op.drop_index(op.f('ix_diy_guides_part_id'), table_name='diy_guides')
    op.drop_index(op.f('ix_diy_guides_bike_id'), table_name='diy_guides')
    op.drop_table('diy_guides')
    op.drop_index(op.f('ix_parts_category'), table_name='parts')
    op.drop_index(op.f('ix_parts_bike_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_contributions_contributor_id'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_bikes_model'), table_name='bikes')
    op.drop_index(op.f('ix_bikes_make'), table_name='bikes')
    op.drop_table('bikes')
    # ### end Alembic commands ###
