"""TVS Apache RTR 160 4V (2018-2023) — 26 parts covering FI, dual-channel ABS, petal discs."""

from seeds.seed_types import PartDef

BIKE_SLUG = "apache_rtr_160_4v"

PARTS: list[PartDef] = [
    # ── AIR INTAKE ──────────────────────────────────────────────────────────
    PartDef(
        name="Air Filter Element",
        category="air_intake",
        function="Dual-layer paper-cotton element filters intake air before the throttle body, protecting injectors and throttle plate from grit that would score the bore.",
        failure_consequences="Clogged element: rich AFR, ECU trims fuel but hits limit — black smoke and misfires. Missing element: abrasive dust ingested through throttle body damages injector needle seat and cylinder bore within 3,000-5,000 km.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Unclip airbox cover (no tools needed on RTR 160 4V), remove element, tap clean or replace. Do NOT wash paper elements with water — replace if visibly black. TVS recommends replacement every 8,000 km.",
        cost_min=200,
        cost_max=550,
        connections_to=[("Air Filter Housing", "mounts_on"), ("FI Throttle Body", "feeds_into")],
    ),
    PartDef(
        name="Air Filter Housing",
        category="air_intake",
        function="Rigid plastic airbox channels filtered air from the element to the throttle body intake tract, also suppressing induction noise.",
        failure_consequences="Cracked housing allows unfiltered air bypass — ECU cannot compensate for the unmetered air, causing lean misfire and potential throttle body damage from grit ingestion.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Inspect rubber seals around throttle body inlet. Seal hairline cracks with fuel-resistant silicone. If cracked at mounting tabs, replace housing to prevent air leak.",
        cost_min=800,
        cost_max=1800,
        connections_to=[("FI Throttle Body", "feeds_into")],
    ),
    # ── FUEL INJECTION SYSTEM ───────────────────────────────────────────────
    PartDef(
        name="FI Throttle Body",
        category="fuel",
        function="Controls airflow into the engine via a butterfly valve linked to the throttle cable. Houses the TPS sensor and idle air control passage. TVS RTR 160 4V uses a 26mm throttle body.",
        failure_consequences="Dirty throttle plate causes erratic idle and throttle hesitation. Seized butterfly valve (stuck open): uncontrolled engine acceleration — dangerous. Faulty TPS causes incorrect fueling maps and poor fuel economy.",
        risk_level="STOP",
        diy_fixable=True,
        quick_fix="For dirty plate only: disconnect air intake, spray throttle body cleaner on plate with engine running at fast idle, wipe with lint-free cloth. Do NOT use carb cleaner — damages rubber O-rings. Replacement requires ECU re-mapping at TVS service.",
        cost_min=3500,
        cost_max=8000,
        connections_to=[("Fuel Injector", "receives_from"), ("Air Filter Element", "receives_from")],
        metadata={"bore_mm": 26, "sensor": "TPS"},
    ),
    PartDef(
        name="Fuel Rail",
        category="fuel",
        function="Aluminum tube running at 3.5 bar pressure distributing fuel from the in-tank pump to the injector. Includes a pressure damper to smooth pulsations.",
        failure_consequences="Fuel rail leak: raw petrol near hot engine — immediate fire risk. Low rail pressure (weak pump or regulator failure): poor atomisation at injector, lean misfire, engine ping under load.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=1500,
        cost_max=3500,
        connections_to=[("Fuel Injector", "feeds_into"), ("Fuel Pump", "receives_from")],
        metadata={"operating_pressure_bar": 3.5},
    ),
    PartDef(
        name="Fuel Injector",
        category="fuel",
        function="Solenoid-controlled injector pulses fuel at 3.5 bar pressure in a conical spray pattern into the intake port. Pulse width controlled by ECU based on MAP sensor, TPS, and RPM data.",
        failure_consequences="Clogged injector: lean misfire, rough idle, engine ping. Dead injector: no start. Stuck-open injector: rich flooding, raw fuel in exhaust (catalytic damage), hydrolocking risk if severe.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=2500,
        cost_max=6000,
        connections_to=[("FI Throttle Body", "sprays_into")],
        metadata={"spray_pattern": "conical", "flow_rate_cc_per_min": 95},
    ),
    PartDef(
        name="Fuel Pump",
        category="fuel",
        function="Submersible in-tank electric pump maintains 3.5 bar system pressure and delivers fuel to the rail. Runs for 2 seconds on key-on to prime the system.",
        failure_consequences="Weak pump: fuel starvation above 6,000 RPM — engine cuts abruptly at highway speeds. Failed pump: engine won't start (no prime pulse heard on key-on). Contaminated pump (rust): restricted flow and bearing failure.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=2500,
        cost_max=6500,
        connections_to=[("Fuel Rail", "feeds_into")],
    ),
    # ── BRAKES ──────────────────────────────────────────────────────────────
    PartDef(
        name="Petal Front Disc Rotor",
        category="brakes",
        function="270mm wave/petal-cut floating disc rotor. Petal cutouts reduce unsprung weight by ~15%, improve wet-weather bite by scraping water, and aid heat dissipation. Mounted on a floating carrier for even pad wear.",
        failure_consequences="Warped rotor (from thermal shock — washing hot disc): brake judder and pulsating lever at high speed braking. Worn below 3.5mm minimum: reduced heat capacity causing brake fade under repeated hard stops. Cracked rotor: immediate brake failure.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=2500,
        cost_max=5500,
        connections_to=[("Front Brake Caliper", "connects_to")],
        metadata={"diameter_mm": 270, "min_thickness_mm": 3.5, "type": "floating_petal"},
    ),
    PartDef(
        name="Petal Rear Disc Rotor",
        category="brakes",
        function="240mm petal disc on rear wheel. Apache RTR 160 4V is one of the few 160cc bikes with rear disc, contributing to its ABS performance.",
        failure_consequences="Cracked disc (from hard pothole impact while braking): sudden rear brake loss. Contamination from chain lube overspray: reduced rear braking by 40-60% and ABS activation at low speeds.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=2000,
        cost_max=4500,
        connections_to=[("Rear Brake Caliper", "connects_to")],
        metadata={"diameter_mm": 240, "min_thickness_mm": 3.5, "type": "petal"},
    ),
    PartDef(
        name="Front ABS Wheel Speed Sensor",
        category="brakes",
        function="Hall-effect magnetic sensor mounted on front fork reads the 48-tooth ABS ring on the wheel hub, sending 48 pulses per wheel revolution to the ABS ECU at 1000+ Hz above 15 km/h.",
        failure_consequences="Dirty or gap-misaligned sensor: ABS warning light, ABS system deactivated — loses all skid prevention in emergency stops. Physically damaged sensor (road debris): permanent ABS fault.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Clean sensor face and tone ring with brake cleaner and soft cloth. Check mounting gap: should be 0.5-1.5mm (use feeler gauge). ABS fault codes: read with TVS diagnostic tool at service center.",
        cost_min=800,
        cost_max=2500,
        connections_to=[("ABS Modulator", "signals_to")],
        metadata={"teeth_on_ring": 48, "type": "hall_effect"},
    ),
    PartDef(
        name="Rear ABS Wheel Speed Sensor",
        category="brakes",
        function="Rear wheel speed sensor on swingarm reads 48-tooth ring on rear wheel hub. ABS modulator uses both front and rear signals to compare wheel speeds and detect impending lockup.",
        failure_consequences="Faulty rear sensor: ABS fully deactivated (both channels). Under hard braking without ABS, rear lockup leads to fishtail — particularly dangerous with pillion on board.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Clean tone ring of chain lube buildup (common on rear). Inspect wiring harness along swingarm for chafing — swingarm pivot is a common wear point. Re-route and tape if needed.",
        cost_min=800,
        cost_max=2500,
        connections_to=[("ABS Modulator", "signals_to")],
        metadata={"teeth_on_ring": 48, "type": "hall_effect"},
    ),
    PartDef(
        name="Front Brake Caliper",
        category="brakes",
        function="Dual-piston radially-mounted caliper provides symmetrical clamping force on the 270mm petal disc. Radial mounting reduces caliper flex for better brake feel compared to conventional axial mounting.",
        failure_consequences="Seized piston: constant brake drag — disc and pads overheat within 10 km, tyre heat increases blowout risk. Failed piston seal: progressive fluid loss, spongy lever leading to total front brake loss.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=4000,
        cost_max=9000,
        connections_to=[("ABS Modulator", "hydraulic_circuit")],
        metadata={"piston_count": 2, "mounting": "radial"},
    ),
    PartDef(
        name="Rear Brake Caliper",
        category="brakes",
        function="Single-piston sliding caliper on the rear disc. Operated by foot lever via a separate hydraulic circuit from the front.",
        failure_consequences="Seized caliper: rear brake drag causes premature tyre wear and overheating of rear disc. Failed seal: fluid leak at rear circuit — loss of rear braking, but front brake remains functional.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=2000,
        cost_max=5000,
        connections_to=[("Rear Brake Master Cylinder", "hydraulic_circuit")],
        metadata={"piston_count": 1, "type": "sliding"},
    ),
    PartDef(
        name="Rear Brake Master Cylinder",
        category="brakes",
        function="Foot-pedal operated master cylinder generates hydraulic pressure for the rear brake caliper circuit.",
        failure_consequences="Seal failure: spongy rear brake pedal, fluid leak onto rear wheel/tyre — tyre contamination causes sudden rear traction loss. Pushrod binding: brake drags constantly.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=800,
        cost_max=2500,
        connections_to=[("Rear Brake Caliper", "supplies_to")],
    ),
    PartDef(
        name="ABS Modulator",
        category="brakes",
        function="Dual-channel hydraulic control unit with solenoid valves modulates brake pressure independently to front and rear circuits during ABS intervention, cycling up to 10 times/second to prevent wheel lockup.",
        failure_consequences="Modulator failure: both ABS channels offline. In worst case, solenoid valve fails closed — partial brake circuit blockage reducing braking force. Replacement is the most expensive brake component on the bike.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=8000,
        cost_max=25000,
        connections_to=[("Front ABS Wheel Speed Sensor", "receives_from"), ("Rear ABS Wheel Speed Sensor", "receives_from")],
        metadata={"channels": 2, "activation_rate_hz": 10},
    ),
    # ── COOLING / OIL ───────────────────────────────────────────────────────
    PartDef(
        name="Oil Filter",
        category="cooling",
        function="Spin-on cartridge filter in the RTR's oil-cooled engine circuit. Oil flows through the external oil cooler before the filter, so the filter handles pre-cooled oil.",
        failure_consequences="Bypass opens when clogged: unfiltered metallic particles circulate through the 4V head's dual camshafts and four valves, causing accelerated valve guide and cam lobe wear.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Replace at every oil change (4,000 km on semi-synthetic). Use TVS genuine filter or Bosch equivalent. When refitting: hand-tight + 3/4 turn only — oil filter overtightening is the most common cause of stripped sump threads.",
        cost_min=180,
        cost_max=450,
        connections_to=[("Engine Oil Drain Plug", "oil_circuit")],
    ),
    PartDef(
        name="Engine Oil Drain Plug",
        category="cooling",
        function="M14x1.5 magnetic drain bolt sealing the RTR's sump. Magnetic tip collects ferrous particles from cam chain, valvetrain, and crankshaft bearings.",
        failure_consequences="Stripped threads (common from overtightening) cause persistent oil leak. Cross-threaded plug on aluminium sump casing requires helicoil thread insert — labour intensive and costly.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Always replace copper gasket washer on reassembly. Torque to 20 Nm maximum on the RTR aluminium sump. Check magnetic tip after draining — fine grey powder is normal; large silver chips indicate engine wear.",
        cost_min=60,
        cost_max=180,
        connections_to=[("Oil Filter", "oil_circuit")],
    ),
    # ── DRIVETRAIN ──────────────────────────────────────────────────────────
    PartDef(
        name="Drive Chain",
        category="drivetrain",
        function="428H pitch O-ring sealed chain. Apache RTR 160 4V produces 15.6 Nm torque — an O-ring chain is mandatory to handle consistent sport riding loads.",
        failure_consequences="Stretched beyond spec: power-robbing slack causes the chain to skip under hard acceleration. Chain snap at race speeds locks rear wheel violently — almost certain crash.",
        risk_level="STOP",
        diy_fixable=True,
        quick_fix="Lube every 500 km with wax-based chain lube (NOT WD-40 — dissolves O-ring grease). Check slack: 10-15mm at mid-span. Replace chain and both sprockets together — fitting new chain on worn sprockets halves the new chain's lifespan.",
        cost_min=1200,
        cost_max=2800,
        connections_to=[("Rear Sprocket", "drives")],
        metadata={"pitch": "428H", "links": 128, "type": "O-ring_heavy"},
    ),
    PartDef(
        name="Front Sprocket",
        category="drivetrain",
        function="16-tooth countershaft sprocket on gearbox output shaft drives the chain. RTR uses one more tooth than Pulsar 150 for higher top speed.",
        failure_consequences="Worn teeth create chain jump under acceleration. Loose lock plate bolt allows sprocket to rotate on shaft — immediate loss of drive.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=350,
        cost_max=700,
        connections_to=[("Drive Chain", "drives")],
        metadata={"teeth": 16, "pitch": "428H"},
    ),
    PartDef(
        name="Rear Sprocket",
        category="drivetrain",
        function="42-tooth aluminium rear sprocket on hub. RTR uses lighter aluminium vs steel for reduced unsprung weight, improving suspension response.",
        failure_consequences="Aluminium sprocket wears faster than steel — replace at 15,000-20,000 km. Worn teeth increase chain skip risk at high RPM. Loose mounting bolts cause sprocket wobble that misaligns and snaps the chain.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=500,
        cost_max=1200,
        connections_to=[("Front Sprocket", "paired_with")],
        metadata={"teeth": 42, "material": "aluminium", "pitch": "428H"},
    ),
    # ── ELECTRICAL ──────────────────────────────────────────────────────────
    PartDef(
        name="LED Headlight Assembly",
        category="electrical",
        function="Multi-LED projector headlight with DRL (Daytime Running Light) strip. Draws 18W vs 35W for halogen, reducing electrical load on the charging system.",
        failure_consequences="Failed LED array: no road illumination at night — illegal and dangerous. DRL failure reduces daytime visibility to oncoming traffic. Fogged lens (internal condensation): 50% reduction in effective beam reach.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=3500,
        cost_max=8000,
        connections_to=[("Battery", "draws_from")],
        metadata={"type": "LED_projector", "wattage": 18, "drl": True},
    ),
    PartDef(
        name="LED Tail Light Assembly",
        category="electrical",
        function="Full-LED tail and brake light cluster. Brake light activates both circuits for brighter stop signal. Also integrates turn indicators on some variants.",
        failure_consequences="Brake light failure: rear-end collision risk from following traffic not seeing braking. Tail light failure: illegal in India, reduces night rear visibility. Both are traffic challan offences.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="LED clusters are sealed units — if any LED section fails, replace entire unit. Check connector for corrosion first (common in monsoon). Check 5A tail light fuse in fuse box.",
        cost_min=1500,
        cost_max=4000,
        connections_to=[("Battery", "draws_from")],
        metadata={"type": "full_LED"},
    ),
    PartDef(
        name="Battery",
        category="electrical",
        function="12V 7Ah MF (Maintenance Free) VRLA battery. Smaller than Pulsar 150 because the RTR's alternator produces more current — battery requires less reserve capacity.",
        failure_consequences="Dead battery: no FI prime pulse, no start, no ABS system initialization. Overcharged battery (faulty regulator/rectifier): electrolyte vents through VRLA safety valve — battery swells and loses capacity permanently.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Test with multimeter: 12.6V resting = healthy. Check regulator/rectifier output: 13.8-14.5V at 3,000 RPM. If overcharging (>15V), replace rectifier before fitting new battery. Amara Raja/Exide MF-7 recommended.",
        cost_min=1500,
        cost_max=3000,
        connections_to=[("ECU", "powers"), ("LED Headlight Assembly", "powers")],
        metadata={"voltage": 12, "capacity_ah": 7, "type": "VRLA_MF"},
    ),
    PartDef(
        name="Spark Plug",
        category="electrical",
        function="Iridium centre electrode plug for the RTR's high-compression (9.4:1) twin-cam 4-valve engine. Iridium tip fires reliably across a wider gap, supporting the RTR's race-derived ignition map.",
        failure_consequences="Fouled plug: misfires at high RPM (most noticeable above 7,000 RPM). Gap erosion on iridium: weak spark causes partial burn — unburned fuel in exhaust harms catalytic converter. Replace every 18,000 km minimum.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Use NGK CPR8EAIX-9 or TVS OEM iridium plug only — do NOT fit standard copper-tip plugs (incorrect heat range for 4V head). Set gap to 0.8-0.9mm. Torque to 12-15 Nm. Do not use anti-seize compound on iridium plugs.",
        cost_min=200,
        cost_max=500,
        connections_to=[("ECU", "controlled_by")],
        metadata={"type": "iridium", "gap_mm": 0.85, "oem": "NGK CPR8EAIX-9"},
    ),
    PartDef(
        name="ECU",
        category="electrical",
        function="32-bit Engine Control Unit manages fuel injection, ignition timing, idle speed control, ABS coordination, and self-diagnostics. Stores fault codes accessible via TVS scan tool.",
        failure_consequences="ECU failure: bike won't start or runs on limp-home map at reduced power. Corrupted firmware: random misfires, ABS faults, incorrect fueling. Water ingress (common on swingarm-mounted ECUs): corrosion of PCB traces.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=8000,
        cost_max=20000,
        connections_to=[("Spark Plug", "signals_to"), ("Fuel Injector", "controls")],
        metadata={"bits": 32, "obd": True},
    ),
    # ── EXHAUST ─────────────────────────────────────────────────────────────
    PartDef(
        name="Race Exhaust Header Pipe",
        category="exhaust",
        function="Tuned-length single-piece stainless header with specific primary pipe diameter (28mm) calculated for peak torque at 6,000 RPM via exhaust scavenging effect. Ceramic-coated on RTR variants.",
        failure_consequences="Cracked primary: exhaust leak causes 6-8% power loss from lost scavenging. Hot gases leak near right footpeg — severe burn risk. Loose header nut causes progressive crack at collector junction.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Inspect header/cylinder head joint for black sooty residue (exhaust leak indicator). Torque header nuts to 20-25 Nm in cross pattern. Replace crush gasket at header/head joint if leaking — ₹80-₹150 at TVS service.",
        cost_min=4000,
        cost_max=9000,
        connections_to=[("Exhaust Muffler", "connects_to")],
        metadata={"primary_bore_mm": 28, "coating": "ceramic"},
    ),
    PartDef(
        name="Exhaust Muffler",
        category="exhaust",
        function="Side-mounted under-seat muffler with catalytic converter (BS6 variants) and perforated core baffle. TVS racing-inspired design reduces back-pressure compared to earlier Apache models.",
        failure_consequences="Carbon-blocked catalyst: power loss and poor throttle response from back pressure increase. Perforated core failure: noise exceeds 80 dB legal limit. Mounting bracket crack causes muffler sag hitting swingarm.",
        risk_level="SAFE",
        diy_fixable=False,
        quick_fix=None,
        cost_min=5000,
        cost_max=12000,
        connections_to=[("Race Exhaust Header Pipe", "receives_from")],
    ),
    # ── SUSPENSION ──────────────────────────────────────────────────────────
    PartDef(
        name="Front Telescopic Fork",
        category="suspension",
        function="37mm conventional telescopic fork with slightly stiffer spring rate (2.4 N/mm) vs commuter bikes for sport riding. Provides 130mm travel with internal rebound damping.",
        failure_consequences="Oil seal leak: fork oil on petal disc causes total front brake failure — STOP immediately. Bent fork tube (pothole impact): steering pulls, can cause tank-slapper at speed. Worn bushes: front-end weave above 80 km/h.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=4000,
        cost_max=12000,
        connections_to=[("Petal Front Disc Rotor", "carries")],
        metadata={"diameter_mm": 37, "travel_mm": 130, "spring_rate_nm": 2.4},
    ),
    PartDef(
        name="Rear Mono-shock",
        category="suspension",
        function="Single gas-charged mono-shock with preload adjustment (5 settings). Linkage-assisted for progressive spring rate — soft initial stroke stiffens under heavy compression.",
        failure_consequences="Blown shock: rear bounces uncontrollably over bumps, rear tyre skips under braking — ABS activates unnecessarily. Fully collapsed shock bottoms out on hard bumps causing structural frame impact.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=3000,
        cost_max=8000,
        connections_to=[("Rear Sprocket", "mounts_near")],
        metadata={"type": "mono_gas_charged", "preload_settings": 5},
    ),
]
