"""Bajaj Pulsar 150 (2018-2023) — 25 parts covering all major systems."""

from seeds.seed_types import PartDef

BIKE_SLUG = "pulsar_150"

PARTS: list[PartDef] = [
    # ── AIR INTAKE ──────────────────────────────────────────────────────────
    PartDef(
        name="Air Filter Element",
        category="air_intake",
        function="Filters dust and debris from intake air before entering the carburetor, protecting engine internals from abrasive particles.",
        failure_consequences="Clogged element restricts airflow causing rich fuel mixture, black exhaust smoke, 20-25% mileage drop, rough idle, and accelerated carburetor jet fouling.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Open airbox cover (2 Phillips screws on left side), pull out foam element, tap firmly on ground to loosen dust. Replace if black or oily. Refit and secure cover.",
        cost_min=150,
        cost_max=400,
        connections_to=[("Air Filter Housing", "mounts_on"), ("Carburetor", "feeds_into")],
    ),
    PartDef(
        name="Air Filter Housing",
        category="air_intake",
        function="Sealed plastic box that houses the air filter element and channels clean air into the carburetor inlet.",
        failure_consequences="Crack or broken seal allows unfiltered air to bypass the element, ingesting road dust directly into the carburetor and causing premature engine wear within 5,000-10,000 km.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Inspect housing for cracks with a torch. Temporary fix: seal hairline cracks with silicone sealant. Permanent fix: replace housing unit (₹600-₹1,200 at Bajaj service).",
        cost_min=600,
        cost_max=1200,
        connections_to=[("Carburetor", "feeds_into"), ("Engine Breather Hose", "receives_from")],
    ),
    PartDef(
        name="Engine Breather Hose",
        category="air_intake",
        function="Routes crankcase blow-by gases (combustion vapour that passes piston rings) back into the airbox for re-combustion instead of venting to atmosphere.",
        failure_consequences="Cracked or disconnected hose causes oily mist in the engine bay, oil drips on the exhaust (fire/smoke risk), slight rich mixture from excess blow-by vapour, and fails emission test.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Trace the rubber hose from the crankcase breather nipple to airbox. If cracked, wrap with self-amalgamating tape as temporary fix. Replace hose at next service (₹100-₹250).",
        cost_min=100,
        cost_max=250,
        connections_to=[("Air Filter Housing", "feeds_into")],
    ),
    # ── FUEL SYSTEM ─────────────────────────────────────────────────────────
    PartDef(
        name="Carburetor",
        category="fuel",
        function="Mixes petrol and air in the correct ratio (approximately 14.7:1) for combustion across all throttle positions and engine speeds.",
        failure_consequences="Dirty main jet causes flat-spot mid-throttle and high fuel consumption. Stuck float valve floods engine with raw fuel (fire hazard, hydrolocking). Worn needle causes rich surge at part throttle.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="For clogged jets: remove bowl (10mm bolt), spray carb cleaner through jets, blow through with compressed air. Do NOT attempt full needle or emulsion tube adjustment without a service manual.",
        cost_min=800,
        cost_max=3500,
        connections_to=[("Air Filter Element", "receives_from"), ("Spark Plug", "fuel_air_delivery")],
        metadata={"type": "CV_carburetor", "model": "Mikuni BS26"},
    ),
    PartDef(
        name="Fuel Tank",
        category="fuel",
        function="Stores up to 15 litres of petrol and feeds the fuel system via the petcock. Tank is steel with chrome knee pads on Pulsar 150.",
        failure_consequences="Pin-hole rust leak is a fire and explosion hazard — stop immediately. Internal rust flakes block the petcock and fuel filter, starving the engine. Dented tank may crack welds.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=3500,
        cost_max=7000,
        connections_to=[("Petcock / Fuel Tap", "feeds_into")],
    ),
    PartDef(
        name="Petcock / Fuel Tap",
        category="fuel",
        function="Manual valve controlling fuel flow from tank to carburetor. Has ON (main reserve), OFF, and RES (reserve 1.5L) positions.",
        failure_consequences="Stuck open: raw fuel floods carburetor when parked, washing cylinder walls and diluting engine oil. Stuck closed or clogged diaphragm: engine dies within minutes of startup from fuel starvation.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="If engine starves at speed: switch to RES. If stuck open flooding carb: turn OFF when parked. Clean petcock by removing and blowing compressed air through all ports. Replace diaphragm kit if seeping (₹150-₹300).",
        cost_min=200,
        cost_max=600,
        connections_to=[("Fuel Filter", "feeds_into")],
    ),
    PartDef(
        name="Fuel Filter",
        category="fuel",
        function="Inline filter (clear bowl type) traps rust particles and sediment from the fuel tank before they reach the carburetor jets.",
        failure_consequences="Clogged filter causes progressive fuel starvation: bike runs fine at low throttle but cuts out under hard acceleration or at high speed. Tank rust particles bypass and block carburetor main jet.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Clamp fuel line both sides of filter, remove filter, hold to light and check bowl — if brown/black, replace. ₹80-₹200 at any spare parts shop. Replace every 6 months or 6,000 km.",
        cost_min=80,
        cost_max=200,
        connections_to=[("Carburetor", "feeds_into")],
    ),
    # ── COOLING / OIL SYSTEM ────────────────────────────────────────────────
    PartDef(
        name="Engine Oil Drain Plug",
        category="cooling",
        function="Magnetic M12x1.5 bolt sealing the engine sump. Magnet collects ferrous metal particles suspended in oil before they circulate through bearings.",
        failure_consequences="Stripped drain plug threads cause persistent oil leak and potential catastrophic oil loss while riding. Cross-threaded plug damages the sump casting requiring costly helicoil repair or sump replacement.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Always use a new copper washer on reassembly. Torque to 20-25 Nm (hand tight + 1/4 turn). If stripped, use an oversized drain plug kit (₹200-₹400) — do NOT overtighten. Check for seeping after every oil change.",
        cost_min=50,
        cost_max=150,
        connections_to=[("Oil Filter", "oil_circuit")],
    ),
    PartDef(
        name="Oil Filter",
        category="cooling",
        function="Spin-on paper element filter removes metal particles and carbon deposits from engine oil, maintaining oil cleanliness between changes.",
        failure_consequences="Clogged filter causes bypass valve to open, circulating unfiltered dirty oil through main bearings and camshaft. Results in accelerated bore wear and bearing failure audible as knocking within 5,000-10,000 km.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Replace with every oil change (every 3,000 km for mineral oil). Hand-tighten filter plus 3/4 turn — never use a wrench to tighten. Use Bajaj genuine filter or reputable brand (Bosch/Mann). Cost ₹150-₹350.",
        cost_min=150,
        cost_max=350,
        connections_to=[("Engine Oil Drain Plug", "oil_circuit")],
    ),
    # ── DRIVETRAIN ──────────────────────────────────────────────────────────
    PartDef(
        name="Drive Chain",
        category="drivetrain",
        function="428 pitch O-ring sealed chain transfers power from gearbox sprocket to rear wheel. O-ring seals retain grease between link plates.",
        failure_consequences="Excessive slack (over 20mm) causes chain slap, power loss, and unpredictable snapping under load. Snapped chain at speed locks the rear wheel instantly — high crash risk. Worn O-rings accelerate stretch.",
        risk_level="STOP",
        diy_fixable=True,
        quick_fix="Check slack: push chain mid-span, should deflect 10-20mm. Adjust via rear axle nuts and chain adjuster bolts. Lube with chain-specific wax spray every 500 km. Replace chain if it can be pulled >2mm from rear sprocket tooth.",
        cost_min=700,
        cost_max=1800,
        connections_to=[("Rear Sprocket", "drives")],
        metadata={"pitch": "428", "links": 128, "type": "O-ring"},
    ),
    PartDef(
        name="Front Sprocket",
        category="drivetrain",
        function="15-tooth countershaft sprocket bolted to the gearbox output shaft, driving the chain and ultimately the rear wheel.",
        failure_consequences="Hooked or shark-finned teeth cause chain to skip under acceleration — sudden loss of drive. Severely worn sprocket accelerates chain stretch and can cause chain to derail onto engine cover.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=300,
        cost_max=600,
        connections_to=[("Drive Chain", "drives")],
        metadata={"teeth": 15, "pitch": "428"},
    ),
    PartDef(
        name="Rear Sprocket",
        category="drivetrain",
        function="44-tooth sprocket bolted to the rear wheel hub, receiving drive from the chain and rotating the rear wheel.",
        failure_consequences="Worn teeth cause chain jumping under acceleration and braking. Hooked teeth can grab and snap the chain. Loose mounting bolts allow sprocket wobble that accelerates chain wear and can cause misalignment.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=400,
        cost_max=900,
        connections_to=[("Front Sprocket", "paired_with")],
        metadata={"teeth": 44, "pitch": "428"},
    ),
    PartDef(
        name="Chain Adjuster Bolt",
        category="drivetrain",
        function="Rear axle adjustment bolt and locking nut on swingarm slot. Moves the rear axle position to compensate for chain stretch and maintain correct tension.",
        failure_consequences="Backed-out adjuster allows excessive chain slack → chain jump and potential snap. Over-tightened chain increases stress on wheel bearings, swingarm bearings, gearbox output shaft, and wears chain 3x faster.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Use alignment marks on both sides of swingarm to ensure equal adjustment. Correct slack: 10-20mm at mid-span. Torque axle nut to 65-80 Nm after adjustment. Check alignment — misaligned chain wears tyres unevenly.",
        cost_min=50,
        cost_max=150,
        connections_to=[("Drive Chain", "adjusts")],
    ),
    # ── BRAKES ──────────────────────────────────────────────────────────────
    PartDef(
        name="Front Brake Disc",
        category="brakes",
        function="260mm solid steel rotor providing the friction surface for the front caliper. Pulsar 150 uses a solid petal-cut disc for heat dissipation.",
        failure_consequences="Warped disc causes rhythmic pulsation through the lever and extended stopping distances. Scored disc (from metal-on-metal contact after pad failure) loses braking efficiency by 30-40%. Minimum thickness: 3.5mm.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=1200,
        cost_max=2800,
        connections_to=[("Front Brake Caliper", "connects_to")],
        metadata={"diameter_mm": 260, "min_thickness_mm": 3.5},
    ),
    PartDef(
        name="Front Brake Caliper",
        category="brakes",
        function="Single-piston sliding caliper squeezes brake pads onto the front disc when hydraulic pressure is applied from the master cylinder.",
        failure_consequences="Seized caliper piston causes constant brake drag: tyre and disc overheat, fuel economy drops 15-20%, brake fade under sustained use. Failed piston seal allows fluid past, resulting in total front brake loss.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=800,
        cost_max=6000,
        connections_to=[("Front Brake Master Cylinder", "hydraulic_circuit")],
        metadata={"piston_count": 1, "type": "sliding"},
    ),
    PartDef(
        name="Front Brake Master Cylinder",
        category="brakes",
        function="Converts lever pressure into hydraulic pressure via a piston and seal, pushing brake fluid through the line to the caliper.",
        failure_consequences="Internal seal failure causes spongy lever with no braking: lever travels to handlebar without stopping power. External seal leak sprays corrosive brake fluid on fork legs (damaging seals) and brake disc (total brake loss).",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=600,
        cost_max=2000,
        connections_to=[("Brake Fluid Reservoir", "draws_from")],
    ),
    PartDef(
        name="Brake Fluid Reservoir",
        category="brakes",
        function="Small translucent reservoir on the handlebar storing DOT 4 brake fluid for the front hydraulic circuit. Fluid level drops gradually as pads wear.",
        failure_consequences="Empty reservoir allows air into the hydraulic circuit causing complete brake lever sponge and loss of braking. Contaminated (moisture-absorbed) fluid boils under sustained braking — vapour compresses, causing sudden brake fade.",
        risk_level="STOP",
        diy_fixable=True,
        quick_fix="Check level through translucent body — must be between MIN and MAX lines. Top up with fresh DOT 4 only (never DOT 3 or DOT 5.1). Do NOT use brake fluid from an open bottle older than 1 year — it absorbs moisture.",
        cost_min=80,
        cost_max=200,
        connections_to=[("Front Brake Caliper", "supplies_to")],
    ),
    # ── ELECTRICAL ──────────────────────────────────────────────────────────
    PartDef(
        name="Battery",
        category="electrical",
        function="12V 9Ah sealed lead-acid battery provides starting current and powers all electrical systems when the engine is off.",
        failure_consequences="Dead battery: engine won't crank, no lights, horn, or instrument cluster. Weak battery causes difficult starting, dim lights at idle, and erratic CDI behavior causing random misfires. Sulfated battery cannot hold charge.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Clean terminal corrosion with baking soda solution and wire brush. Check voltage with multimeter: 12.6V = full, below 12V = charge immediately. If voltage drops below 11V under load, replace battery. Exide/Amara Raja brands recommended.",
        cost_min=1200,
        cost_max=2800,
        connections_to=[("CDI Unit", "powers"), ("Headlight Assembly", "powers")],
        metadata={"voltage": 12, "capacity_ah": 9, "type": "SLA"},
    ),
    PartDef(
        name="Spark Plug",
        category="electrical",
        function="Ignites the compressed air-fuel mixture in the combustion chamber via a high-voltage spark across the 0.7-0.8mm electrode gap.",
        failure_consequences="Fouled plug (black/oily): hard starting, misfires under load, poor power. Gap erosion: weak spark, rough idle, increased fuel consumption. Total failure: engine won't start. Inspect every 6,000 km, replace every 12,000 km.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Remove plug with 16mm plug spanner. Check electrode color: light tan = healthy; black/sooty = rich mixture (carb issue); white/blistered = lean (dangerous). Set gap to 0.7-0.8mm with feeler gauge. NGK BPR7ES or Champion RN4C recommended.",
        cost_min=80,
        cost_max=250,
        connections_to=[("Exhaust Header Pipe", "combustion_output")],
        metadata={"gap_mm": 0.7, "thread": "M14x1.25", "oem": "NGK BPR7ES"},
    ),
    PartDef(
        name="CDI Unit",
        category="electrical",
        function="Capacitor Discharge Ignition module stores charge and releases a high-voltage pulse to the ignition coil at precisely the right crankshaft position for each combustion cycle.",
        failure_consequences="Failed CDI: engine has no spark and won't start. Intermittent CDI failure causes random engine cut-outs while riding — extremely dangerous in traffic. Incorrect advance curve causes pinging under load and power loss.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=800,
        cost_max=2500,
        connections_to=[("Spark Plug", "signals_to")],
    ),
    PartDef(
        name="Headlight Assembly",
        category="electrical",
        function="35W H4 halogen bulb assembly providing road illumination. Pulsar 150 uses a projector-style lens on newer variants for better beam pattern.",
        failure_consequences="Failed bulb: no road lighting — riding at night illegal and dangerous. Wiring short causes blown main fuse, disabling all electrical systems including instruments and indicators. Cracked lens reduces beam intensity by 40-60%.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="For bulb: remove headlight connector, turn retaining ring, swap H4 bulb without touching glass (oils from skin etch the halogen bulb). Use Phillips PH4 or Osram Night Breaker. Fuse blown: check 10A main fuse in fuse box under seat.",
        cost_min=150,
        cost_max=3500,
        connections_to=[("Battery", "draws_from")],
        metadata={"bulb_type": "H4", "wattage": 35},
    ),
    # ── EXHAUST ─────────────────────────────────────────────────────────────
    PartDef(
        name="Exhaust Header Pipe",
        category="exhaust",
        function="Single stainless-steel pipe from the cylinder head exhaust port carries high-temperature exhaust gases to the muffler. Tuned diameter affects torque delivery.",
        failure_consequences="Cracked or loose header joint: loud popping exhaust leak, raw hot gases escape near rider's right leg (burn risk), loss of exhaust scavenging reduces power by 5-8%, corrosion accelerates at crack point.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Tighten exhaust header nut (17mm) to 25-30 Nm if loose. For cracks: use high-temperature exhaust repair putty as temporary fix (₹150-₹300 at auto shops). Permanent fix: TIG welding or header replacement.",
        cost_min=1500,
        cost_max=4000,
        connections_to=[("Exhaust Muffler", "connects_to")],
    ),
    PartDef(
        name="Exhaust Muffler",
        category="exhaust",
        function="Reduces exhaust noise by expanding gases through baffled chambers. Includes catalytic section on BS6 variants. Chrome finish on standard models.",
        failure_consequences="Perforated/rusted muffler: excessive noise above legal 80 dB limit (police fine risk), hot exhaust gases near rider. Internal packing failure causes raspy tone. Blocked catalytic section (carbon choke) reduces power significantly.",
        risk_level="SAFE",
        diy_fixable=False,
        quick_fix=None,
        cost_min=2500,
        cost_max=6000,
        connections_to=[("Exhaust Header Pipe", "receives_from")],
    ),
    # ── SUSPENSION ──────────────────────────────────────────────────────────
    PartDef(
        name="Front Telescopic Fork",
        category="suspension",
        function="Pair of 37mm conventional telescopic forks provides ~130mm of front suspension travel, absorbs road impacts, and maintains steering geometry under braking.",
        failure_consequences="Oil seal leak: fork oil drips onto front brake disc causing total front brake failure — extremely dangerous. Bent fork leg from pothole impact causes wheel misalignment and heavy steering pull. Worn bushes cause fork judder under braking.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=2000,
        cost_max=8000,
        connections_to=[("Front Brake Disc", "carries")],
        metadata={"diameter_mm": 37, "travel_mm": 130, "type": "conventional_telescopic"},
    ),
    PartDef(
        name="Rear Shock Absorber",
        category="suspension",
        function="Dual-tube gas-charged shock absorber with spring preload adjustment. Provides ~110mm of rear travel and maintains tyre contact under acceleration and braking.",
        failure_consequences="Blown shock (oil-gas separator failure): bike bounces excessively over bumps, rear tyre loses traction mid-corner, significant braking distance increase. Completely seized shock causes harsh ride and accelerated frame fatigue.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=1500,
        cost_max=5000,
        connections_to=[("Drive Chain", "mounts_near")],
        metadata={"travel_mm": 110, "type": "gas_charged_dual"},
    ),
]
