"""Royal Enfield Classic 350 (2021-2023, J-platform) — 26 parts covering the new 349cc FI platform."""

from seeds.seed_types import PartDef

BIKE_SLUG = "re_classic_350"

PARTS: list[PartDef] = [
    # ── AIR INTAKE ──────────────────────────────────────────────────────────
    PartDef(
        name="Air Filter Element",
        category="air_intake",
        function="Large-format dual-layer paper element filters intake air for the 349cc long-stroke FI engine. Larger airbox volume tunes intake resonance for the Classic 350's low-RPM torque character.",
        failure_consequences="Clogged element restricts airflow into the throttle body — ECU fueling trims hit limits causing rich misfire and black smoke. RE's long-stroke combustion is more sensitive to mixture quality than shorter-stroke engines.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Unscrew airbox top cover (4 bolts), lift out element. Tap clean for dust; replace if oily (oil-fouled = check piston rings or breather system). RE recommends replacement every 10,000 km. OEM element ~₹250-₹600.",
        cost_min=250,
        cost_max=600,
        connections_to=[("Air Filter Housing", "mounts_on"), ("FI Throttle Body", "feeds_into")],
    ),
    PartDef(
        name="Air Filter Housing",
        category="air_intake",
        function="Large polymer airbox tuned to reduce induction noise — contributes to the Classic 350's iconic low growl. Routes air from the left side vent to the throttle body.",
        failure_consequences="Cracked housing bypasses the filter, allowing dust ingestion. Detached duct between airbox and throttle body causes large unmetered air leak — ECU cannot compensate, causing extreme lean misfire.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Inspect rubber boot connecting airbox to throttle body (common crack point). Tighten clamp bolt — often loosens from vibration. If boot is cracked, replace boot only (₹200-₹500) before replacing full housing.",
        cost_min=1200,
        cost_max=2500,
        connections_to=[("FI Throttle Body", "feeds_into")],
    ),
    # ── FUEL SYSTEM ─────────────────────────────────────────────────────────
    PartDef(
        name="Fuel Tank",
        category="fuel",
        function="Iconic 13-litre teardrop steel tank. Chrome-ringed knee pads on Classic 350 are welded steel — the weld joint is a known rust initiation point on older models.",
        failure_consequences="Pinhole at chrome ring weld: petrol seeps, fire risk. Internal rust flakes block fuel pump strainer — pump burns out within 2,000-3,000 km of running blocked. Dented tank can crack internal baffles.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=5000,
        cost_max=12000,
        connections_to=[("Fuel Tank Breather Valve", "connects_to"), ("Fuel Pump", "supplies_to")],
    ),
    PartDef(
        name="Fuel Tank Breather Valve",
        category="fuel",
        function="One-way roll-over valve vents fuel tank vapour pressure as fuel warms and expands, while preventing fuel spill if the bike tips over.",
        failure_consequences="Clogged breather (common in dusty environments): vacuum builds in tank as fuel is consumed, halting fuel delivery and stalling the engine at 3-4 litres remaining. Open-stuck breather: continuous petrol vapour odour, fuel odour in storage.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="If bike stalls and restarts immediately after loosening fuel cap: breather is blocked. Remove breather cap, blow through with compressed air from tank side. Replace if membrane torn (₹100-₹350).",
        cost_min=100,
        cost_max=350,
        connections_to=[("Fuel Tank", "vents_from")],
    ),
    PartDef(
        name="FI Throttle Body",
        category="fuel",
        function="38mm bore throttle body — larger than typical 160cc bikes, tuned for the Classic 350's low-RPM torque. Cable-operated butterfly with TPS. Idle air bypass controls warm idle.",
        failure_consequences="Dirty throttle plate: high idle after warm-up, throttle tip-in stumble. Stuck butterfly: uncontrolled acceleration or stall. Faulty TPS: incorrect AFR maps, poor fuel economy (common complaint on 2021-22 models before ECU update).",
        risk_level="STOP",
        diy_fixable=True,
        quick_fix="Clean throttle plate with throttle cleaner (engine off, remove air duct). Lubricate throttle cable at both ends. Check TPS voltage with multimeter: should sweep 0.5V-4.5V smoothly from closed to WOT.",
        cost_min=4000,
        cost_max=9000,
        connections_to=[("Fuel Injector", "receives_from"), ("Air Filter Element", "receives_from")],
        metadata={"bore_mm": 38, "sensor": "TPS"},
    ),
    PartDef(
        name="Fuel Injector",
        category="fuel",
        function="Multi-hole injector delivers fuel into the intake port. ECU varies pulse width 1-15ms based on MAP, TPS, coolant temperature, and IAT sensors.",
        failure_consequences="Clogged injector: hard cold starting, lean stumble above 3,500 RPM. Leaking injector: rich idle, fuel smell when parked. Injector coil failure: engine won't start.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=3500,
        cost_max=7000,
        connections_to=[("FI Throttle Body", "sprays_into")],
    ),
    PartDef(
        name="Fuel Pump",
        category="fuel",
        function="In-tank roller-vane pump maintains 3.5 bar system pressure. The Classic 350 pump module also includes the fuel level sender and fuel filter strainer.",
        failure_consequences="Weak pump: engine cuts above 80 km/h on highway (fuel starvation). Failed pump module: no start, no prime audible on key-on. Strainer clogged by tank rust: accelerated pump failure.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=3000,
        cost_max=7000,
        connections_to=[("FI Throttle Body", "feeds_into")],
        metadata={"pressure_bar": 3.5, "includes_sender": True, "includes_strainer": True},
    ),
    # ── COOLING / OIL ───────────────────────────────────────────────────────
    PartDef(
        name="Engine Oil Filter",
        category="cooling",
        function="External spin-on cartridge filter on the left side of the 349cc engine. RE recommends 3,000 km or 3-month oil change intervals — stricter than most FI bikes due to the long-stroke design running hotter.",
        failure_consequences="Bypass opens when clogged: dirty oil circulates through the long-stroke crank, cam lobes, and valve train. RE's air-oil-cooled engine lacks a water jacket — oil cleanliness is the primary cooling buffer.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Replace every oil change. Use Motul 3000 10W-40 or RE branded oil. Filter position on left side requires a filter wrench for removal if overtightened. Always replace copper sealing washer on oil filter bolt.",
        cost_min=200,
        cost_max=500,
        connections_to=[("Engine Oil Drain Plug", "oil_circuit")],
        metadata={"location": "left_side_engine", "oem_interval_km": 3000},
    ),
    PartDef(
        name="Engine Oil Drain Plug",
        category="cooling",
        function="M14x1.5 magnetic drain bolt at sump bottom. Classic 350's larger 349cc displacement holds 1.5L of oil — more volume means more metal particles collected on magnetic tip between changes.",
        failure_consequences="Cross-threaded plug destroys aluminium sump casting threads — helicoil repair costs ₹1,500-₹3,000 in labour. Overtightened plug warps copper washer, creating a weeping seal that drips oil constantly.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Torque to 20-25 Nm (hand tight + 1/4 turn). RE drain plug thread is frequently damaged by untrained roadside mechanics overtightening. Use a new copper washer every time. Check magnetic tip — silver flakes normal; brass chips = bearing concern.",
        cost_min=50,
        cost_max=200,
        connections_to=[("Engine Oil Filter", "oil_circuit")],
    ),
    # ── BRAKES ──────────────────────────────────────────────────────────────
    PartDef(
        name="Front Disc Brake Caliper",
        category="brakes",
        function="ByBre (Brembo subsidiary) single-piston floating caliper clamping the 300mm front disc. ByBre calipers are specified for better heat resistance matching the Classic 350's extra weight (191 kg wet).",
        failure_consequences="Seized piston (common in coastal/humid areas): constant drag overheats disc and pads, reduces fuel economy by 15-20%, causes uneven tyre wear. Piston seal failure: brake fluid contaminates disc and pads — immediate brake loss.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=3000,
        cost_max=7000,
        connections_to=[("Front Brake Master Cylinder", "hydraulic_circuit")],
        metadata={"brand": "ByBre", "piston_count": 1, "disc_size_mm": 300},
    ),
    PartDef(
        name="Rear Disc Brake Caliper",
        category="brakes",
        function="ByBre single-piston caliper on 270mm rear disc. Classic 350 is heavier than most 350cc singles — rear disc is important for weight management during braking.",
        failure_consequences="Seized rear caliper: rear disc and pads heat up, tyre overheats. At 191 kg wet weight, a stuck rear brake dramatically affects handling under acceleration. Fluid leak: rear brake pedal to floor with no braking.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=2500,
        cost_max=6000,
        connections_to=[("Rear Brake Master Cylinder", "hydraulic_circuit")],
        metadata={"brand": "ByBre", "piston_count": 1, "disc_size_mm": 270},
    ),
    PartDef(
        name="Front Brake Master Cylinder",
        category="brakes",
        function="Lever-operated hydraulic master cylinder generating front brake pressure. Classic 350 uses a larger bore master cylinder (15mm) than typical 160cc bikes to manage the 300mm disc's greater clamping requirements.",
        failure_consequences="Internal seal failure: lever goes to bar with minimal braking — dangerous given the 191 kg weight. External leak: DOT 4 fluid strips paint from fuel tank rapidly (within minutes). Freezing lever (seized pivot): no lever movement.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=1500,
        cost_max=4000,
        connections_to=[("Brake Fluid Reservoir", "draws_from")],
        metadata={"bore_mm": 15},
    ),
    PartDef(
        name="Rear Brake Master Cylinder",
        category="brakes",
        function="Foot-pedal operated master cylinder for the rear hydraulic circuit.",
        failure_consequences="Seal failure: spongy or absent rear brake. Corrosion on pedal pivot causes stiff pedal action and constant slight drag on rear disc.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=1000,
        cost_max=3000,
        connections_to=[("Rear Disc Brake Caliper", "supplies_to")],
    ),
    PartDef(
        name="Brake Fluid Reservoir",
        category="brakes",
        function="Front brake hydraulic fluid reservoir integrated with master cylinder. Fluid level drops as front pads wear — monitoring level indicates pad wear status.",
        failure_consequences="Empty reservoir: air enters circuit causing complete front brake loss. Contaminated fluid (moisture >3%): boiling point drops from 230°C to ~150°C — hard downhill braking causes brake fade suddenly.",
        risk_level="STOP",
        diy_fixable=True,
        quick_fix="Check level via sight glass or remove cap. Must be between MIN-MAX. Top with DOT 4 only. Change fluid every 2 years regardless of level — moisture absorption is invisible. Never mix fluid brands.",
        cost_min=80,
        cost_max=250,
        connections_to=[("Front Disc Brake Caliper", "supplies_to")],
    ),
    PartDef(
        name="Front ABS Wheel Speed Sensor",
        category="brakes",
        function="Hall-effect sensor on front fork reading a 48-tooth exciter ring on the front wheel hub. Feeds wheel speed data to the ABS ECU. Classic 350's extra weight makes ABS more critical than on lighter bikes.",
        failure_consequences="Sensor failure: ABS warning light, full ABS deactivation. Without ABS at 191 kg, front lockup during emergency braking causes the bike to dive and wash out — stopping distance increases dramatically.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Clean sensor face with brake cleaner. Inspect exciter ring for bent teeth (common from kerb impacts). Check wiring along fork leg for abrasion. Correct mounting gap: 0.5-1.5mm.",
        cost_min=1000,
        cost_max=3000,
        connections_to=[("ABS Control Unit", "signals_to")],
        metadata={"teeth": 48, "type": "hall_effect"},
    ),
    PartDef(
        name="Rear ABS Wheel Speed Sensor",
        category="brakes",
        function="Rear wheel speed sensor feeding ABS ECU. Classic 350's low-RPM torque character means it can lock the rear wheel even at moderate braking — rear ABS is particularly valuable.",
        failure_consequences="Sensor failure: ABS fully deactivated. RE Classic 350 rear lockup is unpredictable given its torque characteristics. Wiring harness along swingarm is exposed to chain lube spray.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Inspect wiring harness along swingarm for chain-lube contamination and abrasion. Clean tone ring on rear wheel. Check sensor mounting bolt torque — vibration loosens it over time.",
        cost_min=1000,
        cost_max=3000,
        connections_to=[("ABS Control Unit", "signals_to")],
        metadata={"teeth": 48, "type": "hall_effect"},
    ),
    PartDef(
        name="ABS Control Unit",
        category="brakes",
        function="Dual-channel ABS ECU and hydraulic modulator combined unit manages front and rear brake circuits. J-platform Classic 350 uses Bosch 9M+ ABS unit — same unit as many European motorcycles.",
        failure_consequences="ABS unit failure: both circuits lose electronic assist. Modulator solenoid failure in closed position: brake circuit partial blockage. Extremely expensive — Bosch ABS units are not rebuildable and must be replaced.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=10000,
        cost_max=28000,
        connections_to=[("Front ABS Wheel Speed Sensor", "receives_from"), ("Rear ABS Wheel Speed Sensor", "receives_from")],
        metadata={"brand": "Bosch", "model": "9M+", "channels": 2},
    ),
    # ── DRIVETRAIN ──────────────────────────────────────────────────────────
    PartDef(
        name="Drive Chain",
        category="drivetrain",
        function="520 pitch O-ring sealed chain — heavier pitch than Pulsar/Apache to handle the Classic 350's 27 Nm torque. Requires regular maintenance given RE's recommendation of chain inspection every 1,000 km.",
        failure_consequences="Neglected chain on RE Classic is a frequent breakdown cause. Over-slack chain snaps more easily under the engine's heavy low-RPM torque pulses. Chain snap at low speed causes rear lockup and loss of control.",
        risk_level="STOP",
        diy_fixable=True,
        quick_fix="Lube with SAE 80W chain oil every 500-1,000 km. Correct slack: 20-30mm (more than sport bikes — classic has longer swingarm). Replace chain at 25,000-30,000 km or when it can be pulled >3mm from rear sprocket.",
        cost_min=1500,
        cost_max=3500,
        connections_to=[("Rear Sprocket", "drives")],
        metadata={"pitch": "520", "links": 116, "type": "O-ring", "slack_mm": "20-30"},
    ),
    PartDef(
        name="Front Sprocket",
        category="drivetrain",
        function="23-tooth steel countershaft sprocket. Larger diameter than sport bikes for the Classic 350's lower gear ratios that prioritise low-RPM torque over top speed.",
        failure_consequences="Worn teeth cause chain slippage under hard acceleration. Loose lock plate (common neglect item): sprocket can spin freely on shaft shaft — immediate total loss of drive.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=400,
        cost_max=800,
        connections_to=[("Drive Chain", "drives")],
        metadata={"teeth": 23, "pitch": "520", "material": "steel"},
    ),
    PartDef(
        name="Rear Sprocket",
        category="drivetrain",
        function="43-tooth steel rear sprocket. Steel (vs aluminium on Apache) chosen for durability given the Classic 350's heavy torque and typical long-distance touring use.",
        failure_consequences="Hooked teeth on 520-pitch chain create high snap risk under the 27 Nm torque load. Loose sprocket bolts (6x M8): dangerous sprocket wobble that can throw the chain onto swingarm.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=600,
        cost_max=1500,
        connections_to=[("Front Sprocket", "paired_with")],
        metadata={"teeth": 43, "pitch": "520", "material": "steel"},
    ),
    # ── ELECTRICAL ──────────────────────────────────────────────────────────
    PartDef(
        name="Battery",
        category="electrical",
        function="12V 12Ah MF battery — the largest of the three Phase 1 bikes. Larger capacity needed for the 349cc starter motor and to power the USB port, instrument cluster, and ABS unit simultaneously.",
        failure_consequences="Weak battery: ABS unit fails to initialize on startup — ABS warning light, ABS inactive. Insufficient cranking current: starter motor strains, causing starter motor wear. Dead battery leaves rider stranded.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Test: 12.6V resting, 10V+ under cranking load. Check regulator: 13.8-14.5V at 3,000 RPM. RE Classic batteries drain faster than other bikes if left parked >3 weeks — use a trickle charger in storage. Exide EFB-12 recommended.",
        cost_min=1500,
        cost_max=3500,
        connections_to=[("ECU", "powers"), ("USB Charging Port Wiring Harness", "powers")],
        metadata={"voltage": 12, "capacity_ah": 12, "type": "VRLA_MF"},
    ),
    PartDef(
        name="Spark Plug",
        category="electrical",
        function="NGK LKAR8AI iridium plug for the 349cc long-stroke engine. Long-reach thread fits the deep combustion chamber of the single-cylinder J-platform engine.",
        failure_consequences="Oil-fouled plug (black, wet): indicates worn piston rings — RE Classic 350 has known oil consumption on early J-platform units. Replace plug immediately and investigate ring wear. Gap-eroded plug: hard cold morning starts, common RE complaint.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Use NGK LKAR8AI only — incorrect heat range damages the combustion chamber. Gap: 0.7-0.8mm. Thread: M12x1.25 long reach. Inspect plug colour: oily/wet = ring or valve seal issue; white/chalky = lean condition (check TPS/injector).",
        cost_min=120,
        cost_max=400,
        connections_to=[("ECU", "controlled_by")],
        metadata={"type": "iridium", "gap_mm": 0.75, "oem": "NGK LKAR8AI", "thread": "M12x1.25_long"},
    ),
    PartDef(
        name="ECU",
        category="electrical",
        function="RE proprietary 32-bit ECU manages FI, ignition, ABS integration, and the trip computer on the RE Tripper/console. Mounted under tank on J-platform bikes — moisture exposure risk during pressure washing.",
        failure_consequences="ECU failure: bike stuck in limp mode (5,000 RPM limit) or won't start. Known 2021-22 issue: ECU software version 1.x causes stall at traffic lights — reflash to latest version at RE service resolves it.",
        risk_level="STOP",
        diy_fixable=False,
        quick_fix=None,
        cost_min=10000,
        cost_max=25000,
        connections_to=[("Spark Plug", "signals_to"), ("Fuel Injector", "controls")],
        metadata={"bits": 32, "known_issue": "stall_at_idle_pre_v2_firmware"},
    ),
    PartDef(
        name="Side Stand Sensor",
        category="electrical",
        function="Reed switch sensor at side stand pivot prevents engine start (or cuts engine) if side stand is down while the bike is in gear. Critical safety feature — Classic 350's weight makes a side-stand-down drop dangerous.",
        failure_consequences="Faulty sensor (stuck open): bike won't start in neutral or stalls when put in gear — leaves rider stranded. Bypassed sensor (common DIY 'fix'): engine can be ridden with stand down, stand contacts road in left corner — instant crash.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Clean reed switch contacts at stand pivot (mud and rust are common). Test: bike should start in neutral with stand down, should cut engine if put in gear with stand down. Do NOT bypass the sensor — use it as designed.",
        cost_min=400,
        cost_max=1200,
        connections_to=[("ECU", "signals_to")],
    ),
    PartDef(
        name="USB Charging Port",
        category="electrical",
        function="5V/1A USB-A port on the instrument cluster panel allows charging of phones and GPS during riding. Wired directly from battery through the main harness.",
        failure_consequences="Loose port connector: phone charging cuts out over rough roads. Port short-circuit: blows the USB fuse (5A inline fuse) — loses charging but other systems unaffected. Water ingress in monsoon: corrosion inside port socket.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Check 5A inline USB fuse (located near instrument cluster behind headlight nacelle). If port is loose, tighten mounting nut on back of nacelle. Seal port with a rubber cap when not in use in monsoon.",
        cost_min=300,
        cost_max=900,
        connections_to=[("USB Charging Port Wiring Harness", "connects_to")],
    ),
    PartDef(
        name="USB Charging Port Wiring Harness",
        category="electrical",
        function="Dedicated wiring loom from main harness to USB port, including an inline 5A fuse. Routes through the headlight nacelle along the frame.",
        failure_consequences="Pinched wire (common at nacelle routing point during headlight servicing): short circuit blows fuse, can arc and damage adjacent wiring. Corroded connector at harness junction: intermittent USB function.",
        risk_level="SAFE",
        diy_fixable=True,
        quick_fix="Trace harness from battery-side junction to USB port. Check inline fuse with multimeter. If fuse blown repeatedly, find the pinch point — do NOT use a higher-rated fuse as workaround.",
        cost_min=400,
        cost_max=1200,
        connections_to=[("USB Charging Port", "powers")],
    ),
    # ── EXHAUST ─────────────────────────────────────────────────────────────
    PartDef(
        name="Chrome Exhaust Header Pipe",
        category="exhaust",
        function="Large-diameter (38mm) chrome-plated steel header is one of the Classic 350's most iconic visual features. Tuned length for the 349cc engine's exhaust pulse frequency.",
        failure_consequences="Chrome pitting at the cylinder head clamp (thermal cycling point): rust develops under chrome, causes exhaust gas leak, loud popping/ticking. Joint rust makes removal extremely difficult — seized header nuts break during removal.",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Apply copper anti-seize compound to header nuts during reassembly. Inspect chrome for blistering — early sign of under-chrome rust. Clean and apply exhaust manifold paint to rusty bare steel areas. Do NOT use wire brush on chrome.",
        cost_min=3000,
        cost_max=8000,
        connections_to=[("Exhaust Heat Shield", "connects_to"), ("Exhaust Muffler", "connects_to")],
    ),
    PartDef(
        name="Exhaust Heat Shield",
        category="exhaust",
        function="Chrome-plated steel heat shield bolted over the header pipe on the right side, protecting the rider's right leg from the header's 400-500°C surface temperature.",
        failure_consequences="Missing or cracked heat shield: direct contact with exposed header causes severe leg burn in seconds. Loose shield rattles and can contact the header causing metal wear and noise. Missing shield is illegal in India (safety requirement).",
        risk_level="CAUTION",
        diy_fixable=True,
        quick_fix="Two M6 bolts secure the shield to the header. If loose, retighten to 8-10 Nm. If cracked/missing, replace immediately — do NOT ride without it. Aftermarket replacements available in stainless steel for better rust resistance (₹600-₹1,500).",
        cost_min=500,
        cost_max=1500,
        connections_to=[("Chrome Exhaust Header Pipe", "mounts_on")],
    ),
    PartDef(
        name="Exhaust Muffler",
        category="exhaust",
        function="Torpedo-shaped chrome muffler — the Classic's signature silhouette. BS6 variants include a catalytic converter section. Double-wall construction for thermal insulation.",
        failure_consequences="Perforated inner core: metallic resonance rattle, exhaust noise above legal limits. Catalytic converter failure (blocked): significant power reduction, high exhaust temperatures. Chrome flaking into exhaust stream can temporarily block baffle.",
        risk_level="SAFE",
        diy_fixable=False,
        quick_fix=None,
        cost_min=6000,
        cost_max=15000,
        connections_to=[("Chrome Exhaust Header Pipe", "receives_from")],
    ),
    # ── SUSPENSION ──────────────────────────────────────────────────────────
    PartDef(
        name="Front Telescopic Fork",
        category="suspension",
        function="41mm conventional telescopic fork with 130mm travel. Softer spring rate than sport bikes, tuned for Classic 350's long-distance touring character and absorbing large road surface irregularities at lower speeds.",
        failure_consequences="Oil seal failure (common due to dust accumulation on chrome slider): fork oil on 300mm front disc causes immediate front brake failure — STOP immediately. Bent slider from deep pothole: heavy steering, compromised front ABS effectiveness.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=3000,
        cost_max=10000,
        connections_to=[("Front Disc Brake Caliper", "carries")],
        metadata={"diameter_mm": 41, "travel_mm": 130, "type": "conventional_telescopic"},
    ),
    PartDef(
        name="Rear Twin Shock Absorbers",
        category="suspension",
        function="Dual gas-charged twin shocks with 5-step preload adjustment. Classic 350's twin-shock setup is chosen for the retro aesthetic — provides softer, more comfortable ride vs mono-shock at the expense of handling precision.",
        failure_consequences="One blown shock (asymmetric failure is common): bike leans to the failed side under load, particularly noticeable with pillion. Cornering is unpredictable as one side provides damping and the other doesn't. Both shocks typically need replacing together.",
        risk_level="CAUTION",
        diy_fixable=False,
        quick_fix=None,
        cost_min=2000,
        cost_max=8000,
        connections_to=[("Drive Chain", "mounts_near")],
        metadata={"travel_mm": 88, "type": "twin_gas_charged", "preload_settings": 5},
    ),
]
